ARG RUBY_VERSION=3.2.2

FROM ruby:${RUBY_VERSION}-slim

# OS Level Dependencies
RUN apt-get update -qq \
    && apt-get install -yq --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    libvips \
    curl \
    nodejs \
    npm

ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

WORKDIR /rails-coach/

COPY . /rails-coach/

RUN npm install -g yarn

RUN gem update --system && gem install bundler

RUN bundle install

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]